[tool.poetry]
name = "agent"
version = "0.1.0"
description = ""
authors = ["Marc Mezger <marc.mezger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.191"
streamlit = "^1.23.1"
loguru = "^0.7.0"
omegaconf = "^2.3.0"
aleph-alpha-client = "^3.1.2"
pypdf = "^3.7.1"
chromadb = "^0.3.26"
tiktoken = "^0.3.3"
python-dotenv = "^1.0.0"
httpx = "^0.24.0"
python-multipart = "^0.0.6"
fastapi = "^0.96.0"
openai = "^0.27.6"
jinja2 = "^3.1.2"


[tool.poetry.group.dev.dependencies]
mypy = "^1.2.0"
pytest = "^7.3.1"
pylint = "^2.17.4"
ruff = "^0.0.265"
pytest-asyncio = "^0.21.0"
coverage = "^7.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[settings]
known_third_party = ["aleph_alpha_client", "backend", "dotenv", "fastapi", "httpx", "jinja2", "langchain", "loguru", "numpy", "omegaconf", "pydantic", "pytest", "starlette", "streamlit"]

[mypy]
# Disallow dynamic typing
disallow_any_unimported=true
disallow_any_expr = true
disallow_any_decorated = true
disallow_any_generics = true
disallow_any_explicit = true
disallow_subclassing_any = true

# Disallow untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

# None and optional handling
no_implicit_optional = true

# Configuring warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true

# Misc things
strict_equality = true

# Config file
warn_unused_configs = true

[tool.ruff]
line-length = 170
[tool.pylint]
max-line-length = 170
