[project]
name = "agent"
version = "4.0.0"
description = "Add your description here"
authors = [
    { name = "Marc Fabian Mezger", email = "marc.mezger@gmail.com" }
]
dependencies = [
    "langchain-cohere>=0.2.2",
    "loguru>=0.7.2",
    "omegaconf>=2.3.0",
    "tiktoken>=0.7.0",
    "python-dotenv>=1.0.1",
    "fastapi>=0.112.1",
    "openai>=1.41.0",
    "langchain-qdrant>=0.1.3",
    "uvicorn>=0.30.6",
    "pypdfium2>=4.30.0",
    "ultra-simple-config>=0.1.0",
    "langchain-openai>=0.1.22",
    "langchain-community>=0.2.12",
    "langgraph>=0.2.4",
    "arize-phoenix>=4.24.0",
    "fastembed>=0.3.4",
    "nltk>=3.9.1",
    "lingua-language-detector>=2.0.2",
    "diagrams>=0.23.4",
    "pydantic-settings>=2.7.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.2",
    "yappi>=1.6.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/agent"]
